# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qfM0NrLRtfXs2tPz3MltrIaqwbklV7IO
"""

import pandas as pd
import numpy as np


file_path ='/content/project1.xlsx'
df1 = pd.read_excel(file_path)


print(f"📊 Dataset Shape: {df1.shape[0]} Rows and {df1.shape[1]} Columns\n")


print("🔍 --- Data Diagnosis ---")
print(df1.info())


print("\n👀 --- Top 5 Rows Preview ---")
display(df1.head())

print("--- Missing Values Count Per Column ---")
print(df1.isnull().sum())

df1['CouponCode'] = df1['CouponCode'].fillna('NO_COUPON')


text_columns = df1.select_dtypes(include=['object']).columns

for col in text_columns:
    df1[col] = df1[col].astype(str).str.strip()


print("--- After Cleaning: Missing Values Count ---")
print(df1['CouponCode'].isnull().sum())
print("\nSuccess! Missing values and structural text errors fixed.")

df1['CouponCode'] = df1['CouponCode'].fillna('NO_COUPON')


text_cols = ['Status', 'Customer Name', 'City', 'Product', 'CouponCode']
for col in text_cols:
    if col in df1.columns:
        df1[col] = df1[col].astype(str).str.strip()


print("--- Missing Values After Cleaning ---")
print(df1['CouponCode'].isnull().sum())
print("\nSuccess!")

print("--- Data Types Before Conversion ---")
print(df1[['Quantity', 'UnitPrice', 'TotalPrice']].dtypes)


df1['Quantity'] = pd.to_numeric(df1['Quantity'], errors='coerce').fillna(0).astype(int)
df1['Unit Price'] = pd.to_numeric(df1['UnitPrice'], errors='coerce').fillna(0.0).astype(float)
df1['Total Price'] = pd.to_numeric(df1['TotalPrice'], errors='coerce').fillna(0.0).astype(float)

print("\n--- Data Types After Verification ---")
print(df1[['Quantity', 'UnitPrice', 'TotalPrice']].dtypes)

df1['Date'] = pd.to_datetime(df1['Date'], errors='coerce').dt.strftime('%Y-%m-%d')

cleaned_df = df1[(df1['TotalPrice'] > 0) & (df1['Quantity'] > 0)]


cleaned_df.to_csv('Project1_Cleaned_Data.csv', index=False)

print("Data successfully cleaned and saved to Project1_Cleaned_Data.csv")