# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qfM0NrLRtfXs2tPz3MltrIaqwbklV7IO
"""

import pandas as pd
import numpy as np

# Kyunki aapki file excel (.xlsx) format mein hai
file_path ='/content/project1.xlsx'
df1 = pd.read_excel(file_path)

# 1. Dataset ka size check karne ke liye
print(f"📊 Dataset Shape: {df1.shape[0]} Rows and {df1.shape[1]} Columns\n")

# 2. Columns aur missing values dekhne ke liye
print("🔍 --- Data Diagnosis ---")
print(df1.info())

# 3. Data ka preview
print("\n👀 --- Top 5 Rows Preview ---")
display(df1.head())

# Check karenge ki kis column mein kitni missing (null) values hain
print("--- Missing Values Count Per Column ---")
print(df1.isnull().sum())

# 1. Missing values ko 'NO_COUPON' se fill karna
df1['CouponCode'] = df1['CouponCode'].fillna('NO_COUPON')

# 2. String Cleaning (Extra spaces hatana aur text ko clean rakhna)
# Agar aapke dataset mein 'City' ya 'Status' jaise text columns hain, toh unke extra spaces trim karenge
text_columns = df1.select_dtypes(include=['object']).columns

for col in text_columns:
    df1[col] = df1[col].astype(str).str.strip()

# Verification check ki ab koi missing value bachi toh nahi
print("--- After Cleaning: Missing Values Count ---")
print(df1['CouponCode'].isnull().sum())
print("\nSuccess! Missing values and structural text errors fixed.")

# 1. Missing values ko 'NO_COUPON' se fill karenge (Sahi spelling ke sath)
df1['CouponCode'] = df1['CouponCode'].fillna('NO_COUPON')

# 2. String Cleaning: Saare text columns ke extra spaces trim karenge
text_cols = ['Status', 'Customer Name', 'City', 'Product', 'CouponCode']
for col in text_cols:
    if col in df1.columns:
        df1[col] = df1[col].astype(str).str.strip()

# Verification check
print("--- Missing Values After Cleaning ---")
print(df1['CouponCode'].isnull().sum())
print("\nSuccess!")

# Check numerical types and do conversions if needed
print("--- Data Types Before Conversion ---")
print(df1[['Quantity', 'UnitPrice', 'TotalPrice']].dtypes)

# Data types ko cleanly float aur int mein convert karna (safely handling errors)
df1['Quantity'] = pd.to_numeric(df1['Quantity'], errors='coerce').fillna(0).astype(int)
df1['Unit Price'] = pd.to_numeric(df1['UnitPrice'], errors='coerce').fillna(0.0).astype(float)
df1['Total Price'] = pd.to_numeric(df1['TotalPrice'], errors='coerce').fillna(0.0).astype(float)

print("\n--- Data Types After Verification ---")
print(df1[['Quantity', 'UnitPrice', 'TotalPrice']].dtypes)

df1['Date'] = pd.to_datetime(df1['Date'], errors='coerce').dt.strftime('%Y-%m-%d')

# 4. Filtering out anomalies/outliers
cleaned_df = df1[(df1['TotalPrice'] > 0) & (df1['Quantity'] > 0)]

# 5. Exporting the final cleaned CSV file
cleaned_df.to_csv('Project1_Cleaned_Data.csv', index=False)

print("Data successfully cleaned and saved to Project1_Cleaned_Data.csv")